	package;

	//https://docs.joomla.org/J2.5:Developing_a_MVC_Component/Basic_backend

	import php.Lib;
	import JRequest; //generated by http://phptohaxe.haqteam.com/extern.php and then hand-edited

	//note: had to remove some comments from the source file below because the macro was choking on the word "function" in it.
	@:build(PHP.generateExtern("legacy/controller/legacy.php")) 
	class JControllerLegacy implements Dynamic { }
	
	//this did not convert properly:
	//@:build(PHP.generateExtern("legacy/request/request.php")) 
	//class JRequest implements Dynamic { } 

	class JoomlahaxeController extends JControllerLegacy
	{
		static public function main()
		{
		}

		override public function display(?cachable:Dynamic,?urlparams:Dynamic):Dynamic{
			
			//also works:
			//untyped __php__("JRequest::setVar('view', JRequest::getCmd('view', 'Joomlahaxes'))");

			//had to add "default" and "method" and true below (Joomla defaults) because haxe was passing null and it wasn't working
			JRequest.setVar('view', JRequest.getCmd('view', 'Joomlahaxes',"default"),"method",true);
			
			
			
			// call parent behavior. PHP equivalent is parent::display($cachable);
			super.display(cachable,urlparams);
			return this;
			
			
			
		}
		
		
		
	}
	


